<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mcu_dashboard</name>
  <version>0.1.0</version>
  <description>MCU telemetry dashboard and eight-channel motor command test panel.</description>

  <maintainer email="hang@todo.invalid">hang</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>mcu_protocol_msgs</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <test_depend>ament_pytest</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
